# Site settings
title: Thomas Thoren
description: "Software engineer based in Chicago."
baseurl: ""  # The subpath of your site, e.g. /blog/
url: https://thomasthoren.com   # The base hostname & protocol for your site
enforce_ssl: thomasthoren.com   # without any protocol
github_username:  ThomasThoren
linkedin_username: thomasjthoren
highlighter: rouge
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-seo-tag
collections:
  - clips_design
  - clips_written
  - side_projects
  - talks
  - awards
destination:  ./public
sass:
  sass_dir: _sass
  style: compressed
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "true"
# Extra tags for jekyll-seo-tag:
author: thomasjthoren
