# Site settings
title: Thomas Thoren
description: "Independent journalist in Austin, Texas."
long_description: "Journalist, developer, designer and lecturer in Austin, Texas."
email: thomasjthoren@gmail.com
cell: 504-312-1505
baseurl: ""  # The subpath of your site, e.g. /blog/
url: https://thomasthoren.com   # The base hostname & protocol for your site
enforce_ssl: thomasthoren.com   # without any protocol
twitter_username: thomasjthoren
github_username:  ThomasThoren
highlighter: rouge
markdown: kramdown
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-seo-tag
collections:
  - clips_design
  - clips_written
  - side_projects
  - talks
destination:  ./public
sass:
  sass_dir: _sass
  style: compressed
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "true"
# Extra tags for jekyll-seo-tag:
author: thomasjthoren
twitter:
  username: thomasjthoren
