# Site settings
title: Thomas Thoren
description: "Journalist at The Lens in New Orleans, working as a reporter, developer and designer."
email: thomasjthoren@gmail.com
baseurl: ""  # The subpath of your site, e.g. /blog/
url: http://thomasthoren.com  # The base hostname & protocol for your site
twitter_username: thomasjthoren
github_username:  ThomasThoren
highlighter: pygments
markdown: kramdown
gems:
  - jekyll-sitemap
collections:
  - clips
  - side_projects
destination:  ./public
sass:
  sass_dir: _sass
  style: compressed
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "true"
